"""SETTINGS"""

syntax on "enable syntax highlighting

"jump to last position when reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

set shiftwidth=2 "number of spaces for (auto)indent

set expandtab "use spaces instead of tabs

set ignorecase "do case insensitive matching

set smartcase "do smart case matching

set incsearch "incremental search

set hlsearch

set mouse=a "enable mouse usage (all modes)

set backspace=indent,eol,start "avoid backspace problems (http://vim.wikia.com/wiki/Backspace_and_delete_problems)

set vb "silent bell

set ruler "Show column and line position

let mapleader=','

"""START NEOBUNDLE CONFIGURATION (https://github.com/Shougo/neobundle.vim)"""

if has('vim_starting')
  set rtp+=~/.vim/bundle/neobundle.vim/ "add neobundle path to runtimepath
end

call neobundle#begin(expand('~/.vim/bundle/'))

"neobundle intself
NeoBundleFetch 'Shougo/neobundle.vim'

"GitHub repos
NeoBundle 'othree/html5.vim'
NeoBundle 'scrooloose/nerdtree'
NeoBundle 'tpope/vim-surround'
NeoBundle 'tomtom/tlib_vim'
NeoBundle 'hail2u/vim-css3-syntax'
NeoBundle 'tpope/vim-haml'
NeoBundle 'pangloss/vim-javascript'
NeoBundle 'leshill/vim-json'
NeoBundle 'tpope/vim-rails'
NeoBundle 'tpope/vim-rake'
NeoBundle 'tpope/vim-projectionist'
NeoBundle 'tpope/vim-bundler'
NeoBundle 'vim-ruby/vim-ruby'
NeoBundle 'slim-template/vim-slim'
NeoBundle 'evidens/vim-twig'
NeoBundle 'bronson/vim-visual-star-search'
NeoBundle 'kchmck/vim-coffee-script'
NeoBundle 'godlygeek/tabular'
NeoBundle 'altercation/vim-colors-solarized'
NeoBundle 'othree/xml.vim'
NeoBundle 'embear/vim-localvimrc'
NeoBundle 'Raimondi/delimitMate'
NeoBundle 'vimwiki/vimwiki'
NeoBundle 'endel/vim-github-colorscheme'
NeoBundle 'Valloric/YouCompleteMe'
NeoBundle 'scrooloose/syntastic'
NeoBundle 'christoomey/vim-tmux-navigator'
NeoBundle 'benmills/vimux'
NeoBundle 'tpope/vim-fugitive'
NeoBundle 'scrooloose/nerdcommenter' 
NeoBundle 'tpope/vim-abolish'
NeoBundle 'sirver/ultisnips'
NeoBundle 'honza/vim-snippets'
"NeoBundle 'skalnik/vim-vroom'
NeoBundle 'majutsushi/tagbar'
NeoBundle 'chrisbra/NrrwRgn'
NeoBundle 'terryma/vim-multiple-cursors'
NeoBundle 'Lokaltog/vim-easymotion'
NeoBundle 'tpope/vim-unimpaired'
NeoBundle 'tpope/vim-repeat'
NeoBundle 'tpope/vim-dispatch'
NeoBundle 'danchoi/ri.vim'
NeoBundle 'gabebw/vim-spec-runner'
NeoBundle 'airblade/vim-gitgutter'
NeoBundle 'kien/ctrlp.vim'
"NeoBundle 'waiting-for-dev/vim-www'
NeoBundle '/home/marc/projects/vim/vim-www/', { 'type' : 'nosync' }
NeoBundle 'ludovicchabant/vim-gutentags'
"NeoBundle '/home/marc/projects/test/vim-gutentags/', { 'type' : 'nosync' }
"NeoBundle 'jodosha/vim-devnotes'

"vim-scripts repos
"NeoBundle 'AutoTag'
NeoBundle 'VimRepress'
NeoBundle 'loremipsum'
NeoBundle 'CSApprox'

call neobundle#end()

NeoBundleCheck

filetype plugin indent on

"""PLUGINS CONFIGURATION"""

"tagbar
nmap <leader>g :TagbarToggle<CR>

"gtranslate
let g:goog_user_conf = [{'langpair': 'es|en', 'v_key': 'T'}]

"localvimrc
let g:localvimrc_ask = 0 "do not ask to load local vimrc

"loremipsum
let g:loremipsum_marker = {}
let g:loremipsum_paragraph_template = {
      \ 'html': '<p>%s</p>',
      \ 'php': '<p>%s</p>',
      \ 'slim': 'p %s',
      \ }

"youcompleteme
"let g:EclimCompletionMethod = 'omnifunc' "if using eclim uncomment this line

"syntastic
let g:syntastic_mode_map = { 'mode': 'active',
      \ 'active_filetypes': ['php', 'ruby', 'css', 'html'], }
let g:syntastic_php_checkers = ['php']
let g:syntastic_ruby_checkers = ['ruby', 'rubocop', 'reek']
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 2
let g:syntastic_check_on_open = 1

"vimwiki
let g:vimwiki_list = [{'path': '~/wiki/', 'path_html': '~/wiki_html/', 'syntax': 'markdown', 'ext': '.md'}]

"zoomwin
map <C-x> :ZoomWin<CR>

"ultisnips & youcompleteme
"http://stackoverflow.com/questions/14896327/ultisnips-and-youcompleteme/18685821#18685821
"https://github.com/Valloric/YouCompleteMe/issues/36
"function! g:UltiSnips_Complete()
"  call UltiSnips#ExpandSnippet()
"  if g:ulti_expand_res == 0
"    if pumvisible()
"      return "\<C-n>"
"    else
"      call UltiSnips#JumpForwards()
"      if g:ulti_jump_forwards_res == 0
"        return "\<TAB>"
"      endif
"    endif
"  endif
"  return ""
"endfunction
"au BufEnter * exec "inoremap <silent> " . g:UltiSnipsExpandTrigger . " <C-R>=g:UltiSnips_Complete()<cr>"
let g:UltiSnipsExpandTrigger="<c-j>"
let g:UltiSnipsJumpForwardTrigger="<c-j>"
let g:UltiSnipsJumpBackwardTrigger="<c-k>"
let g:UltiSnipsListSnippets="<c-e>"
" this mapping Enter key to <C-y> to chose the current highlight item 
" and close the selection list, same as other IDEs.
" CONFLICT with some plugins like tpope/Endwise
"inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"

"vim-vroom
"let g:vroom_use_spring=1
"let g:vroom_use_vimux=1

"vimux
map <Leader>l :VimuxRunLastCommand<CR>

"buffergator
let g:buffergator_viewport_split_policy='T'
let g:buffergator_sort_regime='mru'

"fugitive
nmap <leader>gg :Git 
nmap <leader>gs :Gstatus<CR>
nmap <leader>gc :Gcommit<CR>
nmap <leader>gr :Gread<CR>
nmap <leader>gw :Gwrite<CR>
nmap <leader>gd :Gdiff<CR>
nmap <leader>g. :Git add .<CR>

"NERDTree
noremap <leader>n :NERDTreeToggle<CR>

"""COLOR SCHEMES"""
"if $TERM == 'xterm'
set t_Co=256
"if using solarized, uncomment following three lines
"set background=light
colorscheme solarized
"if using github, uncomment following three lines
"colorscheme  github
"set background=light
"colorscheme tomorrow
"source $HOME/.vim/colorschemes/tomorrow/colors/Tomorrow-Night-Blue.vim
"endif
" http://sunaku.github.io/vim-256color-bce.html
"set t_ut=

"ri
nnoremap  ,dr :call ri#OpenSearchPrompt(0)<cr> " horizontal split
nnoremap  ,dR :call ri#OpenSearchPrompt(1)<cr> " vertical split
nnoremap  ,dk :call ri#LookupNameUnderCursor()<cr> " keyword lookup

"CtrlP
"Remeber last mode (https://github.com/kien/ctrlp.vim/issues/330)
let g:ctrlp_cmd = 'call CallCtrlP()'

func! CallCtrlP()
  if exists('s:called_ctrlp')
    CtrlPLastMode
  else
    let s:called_ctrlp = 1
    CtrlP
  endif
endfunc

"""OTHER OPTIONS"""

set laststatus=2 "Always show status line

"when writting e-mails with gmail with <<It's All Text>> Firefox plugin
"(https://addons.mozilla.org/En-us/firefox/addon/its-all-text/)
"set textwidth to 80 characters
autocmd BufNewFile,BufRead mail.google.com* set tw=80

"for writing Calibre recipes (http://manual.calibre-ebook.com/news.html)
"which are python classes
autocmd BufNewFile,BufRead *.recipe set ft=python

"rabl templates are ruby files
autocmd BufNewFile,BufRead *.rabl set ft=ruby

"load some personal configuration I don't want in a public repository
if filereadable($HOME.'/.vim/vimrc_private')
  source $HOME/.vim/vimrc_private
endif

"encryption
set cm=blowfish "use blowfish for encryption
autocmd BufNewFile,BufRead *.enc set nobackup noswapfile nowritebackup viminfo= "enc extension will be used for encrypted files

"git
autocmd Filetype gitcommit setlocal spell textwidth=72 "commit messages with spell checking and textwidth
set statusline=%<%f\ %h%m%r%{fugitive#statusline()}%=%-14.(%l,%c%V%)\ %P "add git branch to the status line with fugitive

"command to open easily this file
command! Evimrc e ~/.vim/vimrc
command! Svimrc sp ~/.vim/vimrc
command! Vvimrc vs ~/.vim/vimrc
"command to reload local vim configuration
command! Vimrc source $MYVIMRC

"command to open easily my main zsh config file
command! Eoh e ~/.oh-my-zsh/custom/custom.zsh
command! Soh sp ~/.oh-my-zsh/custom/custom.zsh
command! Voh vp ~/.oh-my-zsh/custom/custom.zsh

"command to reload quickfix window and to reload and jump to last line
:autocmd BufReadPost quickfix nnoremap <buffer> r :Copen<CR>
:autocmd BufReadPost quickfix nnoremap <buffer> R :Copen<CR>G

"mappint to close quickfix windows
nnoremap <F8> :cclose<CR>

"indent all file & return to current line
nnoremap <F9> gg=G''

"clean hlsearch
nnoremap <F12> :nohlsearch<CR>

"force page refresing
nnoremap <F5> :redraw!<CR>

let g:www_urls = {
      \ 'rails' : 'http://guides.rubyonrails.org/',
      \ 'rails_started' : 'http://guides.rubyonrails.org/getting_started.html',
      \ 'rails_active_record' : 'http://guides.rubyonrails.org/active_record_basics.html',
      \ 'rails_migrations' : 'http://guides.rubyonrails.org/migrations.html',
      \ 'rails_validations' : 'http://guides.rubyonrails.org/active_record_validations.html',
      \ 'rails_callbacks' : 'http://guides.rubyonrails.org/active_record_callbacks.html',
      \ 'rails_associations' : 'http://guides.rubyonrails.org/association_basics.html',
      \ 'rails_query' : 'http://guides.rubyonrails.org/active_record_querying.html',
      \ 'rails_view' : 'http://guides.rubyonrails.org/action_view_overview.html',
      \ 'rails_rendering' : 'http://guides.rubyonrails.org/layouts_and_rendering.html',
      \ 'rails_helpers' : 'http://guides.rubyonrails.org/form_helpers.html',
      \ 'rails_controller' : 'http://guides.rubyonrails.org/action_controller_overview.html',
      \ 'rails_routing' : 'http://guides.rubyonrails.org/routing.html',
      \ 'rails_support' : 'http://guides.rubyonrails.org/active_support_core_extensions.html',
      \ 'rails_i18n' : 'http://guides.rubyonrails.org/i18n.html',
      \ 'rails_mailer' : 'http://guides.rubyonrails.org/action_mailer_basics.html',
      \ 'rails_testing' : 'http://guides.rubyonrails.org/testing.html',
      \ 'rails_security' : 'http://guides.rubyonrails.org/security.html',
      \ 'rails_debug' : 'http://guides.rubyonrails.org/debugging_rails_applications.html',
      \ 'rails_config' : 'http://guides.rubyonrails.org/configuring.html',
      \ 'rails_cli' : 'http://guides.rubyonrails.org/command_line.html',
      \ 'rails_assets' : 'http://guides.rubyonrails.org/asset_pipeline.html',
      \ 'rails_js' : 'http://guides.rubyonrails.org/working_with_javascript_in_rails.html',
      \ 'rails_engines' : 'http://guides.rubyonrails.org/engines.html',
      \ 'rails_init' : 'http://guides.rubyonrails.org/initialization.html',
      \ 'rails_plugins' : 'http://guides.rubyonrails.org/plugins.html',
      \ 'rails_rack' : 'http://guides.rubyonrails.org/rails_on_rack.html',
      \ 'rails_generators' : 'http://guides.rubyonrails.org/generators.html',
      \ 'rails_api' : 'http://api.rubyonrails.org/',
      \ 'ruby' : 'http://www.ruby-doc.org/core-2.2.2/',
      \ 'factory_girl' : 'http://www.rubydoc.info/gems/factory_girl/file/GETTING_STARTED.md',
      \ 'capybara' : 'https://github.com/jnicklas/capybara',
      \ 'formtastic': 'https://github.com/justinfrench/formtastic',
      \ 'rspec' : 'http://betterspecs.org/',
      \ 'rspec-mock' : 'https://github.com/rspec/rspec-mocks',
      \ 'shoulda_matchers' : 'https://github.com/thoughtbot/shoulda-matchers',
      \ 'ransack' : 'https://github.com/activerecord-hackery/ransack',
      \ 'pi_ragas' : 'https://www.pivotaltracker.com/n/projects/1054406',
      \ 'pi_ragas_general' : 'https://www.pivotaltracker.com/n/projects/1184952',
      \ 'pi_ragas_almacen' : 'https://www.pivotaltracker.com/n/projects/1184954',
      \ 'pi_hastinik' : 'https://www.pivotaltracker.com/n/projects/1128094',
      \ 'timer' : 'https://www.toggl.com/app/timer',
      \ 'heroku' : 'https://dashboard.heroku.com/',
      \ 'middleman' : 'http://middlemanapp.com/',
      \ 'dragonfly' : 'markevans.github.io/dragonfly/',
      \ 'gh?' : 'https://github.com/search?utf8=%E2%9C%93&ref=simplesearch&q=',
      \ 'enes?' : 'http://www.wordreference.com/es/en/translation.asp?spen=',
      \ 'gem?' : 'rubygems.org/search?query=',
      \ 't?' : 'https://translate.google.de/#ne/de/',
      \ 'o?' : ['https://www.omniref.com/?q='],
      \
      \ }
let g:www_sessions = { 'rails' : ['ruby', 'rails'] }
let g:www_default_search_engine = 'g?'

"tab navigation
nnoremap <leader>tp :tabprevious<CR>
nnoremap <leader>tn :tabNext<CR>
nnoremap <leader>tP :tabfirst<CR>
nnoremap <leader>tN :tablast<CR>

"devnotes
"set statusline +=%{devnotes#statusline()}

"Easily find todo's
nnoremap <leader><leader>t :Ggrep TODO<CR>
